### ISSUE TITLE
The code passes tests, but is shown as Pending

### ISSUE THREAD

**Issue by divijan** [akraievoy/elw#33] opened 2011-12-24 22:57 UTC
That is, it passes tests when tested from student's account, but in the table it appears Pending to both admin and the student.

**Comment by divijan** [comment] 2012-02-19 21:42
This happened to Оксана Базалій & Євген Каліта. In both cases it was code for lab 4.

**Comment by akraievoy** [comment] 2012-03-14 07:05
Apparent dupe of #46

**Closed as completed by akraievoy** 2012-03-14 07:05 UTC
Labels: tier-1-planned

**Comment by divijan** [comment] 2012-03-14 10:31
Nope. If it was, #46 would be fixed too.
